version: '3.8'

services:
  api-server:
    container_name: api-server
    image: ${NCP_CONTAINER_REGISTRY}/${IMAGE_NAME}
    depends_on:
      - redis
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
      - 6379:6379
    env_file: .env

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
