version: '3.8'

services:
  api-server:
    container_name: api-server
    image: ${NCP_CONTAINER_REGISTRY}/${IMAGE_NAME}
    depends_on:
      - redis
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    env_file: .env
    volumes:
      - /logs:/logs

  redis:
    container_name: redis
    image: redis:latest
    expose:
      - ${REDIS_PORT}
    volumes:
      - /data:/data
