name: Configure PR

on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  check-title:
    runs-on: ubuntu-latest

    steps:
      - name: Check Title
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(Feature|Fix|Refactor)\(#\d+(,[\s]*#\d+)*\)\:(.+)$'
          github_token: ${{ secrets.CONFIGURE_PR__PAT }}

  set-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Set Label
        uses: TimonVS/pr-labeler-action@v5
        with:
          repo-token: ${{ secrets.CONFIGURE_PR__PAT }}

  set-issue:
    needs:
      - check-title
    runs-on: ubuntu-latest

    steps:
      - name: Set Issue Number
        uses: actions/github-script@v7
        if: github.event.pull_request.base.ref != 'release'
        with:
          github-token: ${{ secrets.CONFIGURE_PR__PAT }}
          script: |
            const title = context.payload.pull_request.title;
            const issueNumbers = title.match(/#(\d+)/g);
            const prefix = issueNumbers ? issueNumbers.reduce((acc, curr) => `${acc}🚀 resolved ${curr}\n`, "") : '';
            const body = context.payload.pull_request.body.replace(/(🚀 resolved #\d+)+/g, '');

            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.number,
              body: `${prefix}${body}`,
            });

  set-assignee:
    runs-on: ubuntu-latest

    steps:
      - name: Set Assignees
        uses: actions/github-script@v7
        if: github.event.pull_request.base.ref != 'release'
        with:
          github-token: ${{ secrets.CONFIGURE_PR__PAT }}
          script: |
            const sender = context.payload.sender.login;
            const assignees = context.payload.pull_request.assignees;
            const newAssignees = assignees ?? [];
            newAssignees.push(sender);

            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              assignees: newAssignees,
            });

  assign-reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Filter reviewers
        id: filtering
        uses: actions/github-script@v7
        if: github.event.pull_request.base.ref != 'release'
        with:
          github-token: ${{ secrets.CONFIGURE_PR__PAT }}
          script: |
            const sender = context.payload.sender.login;
            const members = ['kimyu0218', 'tmddus2', 'ttobe'];
            const reviewers = members.filter((item) => item !== sender).join(',');
            core.setOutput('reviewers', reviewers);

      - name: Assign reviewers
        uses: hkusu/review-assign-action@v1.4.0
        with:
          github-token: ${{ secrets.CONFIGURE_PR__PAT }}
          reviewers: ${{ steps.filtering.outputs.reviewers }}
